### ISSUE TITLE
Package dependencies for Linux (Debian "bullseye")

### ISSUE THREAD

**Issue by tukkek** [wghost/PatcherGUI#5]
Hello, I had a hard time finding the exact package names for building this project on Debian testing so I thought I'd share a easy to copy-and-paste command line in case you want to add it to the README:

`sudo apt-get install g++ cmake git libwxgtk3.0-gtk3-dev`

Thank you for all the work done on this project!

**Comment by wghost** [comment]
Done. Thanks for sharing.

**Comment by tukkek** [comment]
Thank you, sir!
