### ISSUE TITLE
Redundant parameters make unable to patch

### ISSUE THREAD

**Issue by ghost** [wghost/PatcherGUI#8]
Redundant parameters when using UPKutils and DecompressLZO
from what i grasp from the logs when calling the binaries somethings like this appen :
`"~/PatcherGUI/binaries/DecompressLZO" "xcomgame.UPK" "~/SteamLibrary/steamapps/common/XCom-Enemy-Unknown/xew/xcomgame/cookedpcconsole/xcomgame.upk"`

Due to 3 parameters being present DecompressLZO send the help message instead of decompressing xcomgame.UPK alongside : 
`Unexpected parameter '/SteamLibrary/steamapps/common/XCom-Enemy-Unknown/xew/xcomgame/cookedpcconsole/xcomgame.upk'`

**Comment by wghost** [comment]
Which version of UPKUtils are you using? I did some updates lately and those are not meant to be used with PatcherGUI. From the readme: "The updated versions of the tools might not be working properly with PatcherGUI. Use the v7.3 sources released on Apr 10, 2015 for that purpose."

**Comment by ghost** [comment]
My bad, since i was unable to compile the latest version with cmake i wrongly assumed that it would be the same for the Apr 10, 2015 version. I'm so sorry.
