### ISSUE TITLE
Trying to mod XCOM EU but getting error

### ISSUE THREAD

**Issue by chknatwork** [wghost/PatcherGUI#9]
This might not be the right place but I am having trouble getting the patcher to work.

First off, when I launch this, I get a popup message:

> ../src/common/sizer.cpp(1472): assert "!(flags & (wxALIGN_BOTTOM | wxALIGN_CENTRE_VERTICAL)) || !(flags & (wxALIGN_RIGHT | wxALIGN_CENTRE_HORIZONTAL))" failed in DoInsert(): wxEXPAND flag will be overridden by alignment flags

I assume it's just informing me of something. However, when patching, I get this:

/home/computer/PatcherGUI/binaries/DecompressLZO: error while loading shared libraries: libwx_baseu-3.1.so.5: cannot open shared object file: No such file or directory

I ran echo $LD_LIBRARY_PATH and it shows `/usr/local/lib/` which seems about right. However, it doesn't seem to see where the file is.

Not sure what I am doing wrong at this point.

**Comment by wghost** [comment]
When you launch what? Are you trying to compile from sources?

**Comment by chknatwork** [comment]
Launching the patcher. I was able to compile the sources. It's a popup message after I launch PatcherGUI

**Comment by wghost** [comment]
Be careful on wxwidgets version and make sure you have libraries in path if you're using dynamic linking or just use static linking.

**Comment by chknatwork** [comment]
Any recommendation on which I should use? I just followed the build instructions to compile the source from their wiki.

I use Manjaro so I can't use it from the AUR repos.

Is there another place I can get the source?

**Comment by wghost** [comment]
I used wxGTK-devel v.3.0.

You can always build wxwidgets libraries from the sources, just be careful with build parameters - i.e. static for static linking, etc.

**Comment by chknatwork** [comment]
Should I be using Static or Dynamic? I don't remember exactly what option I used.

**Comment by wghost** [comment]
I prefer static - bigger executable, but no dependencies.

**Comment by chknatwork** [comment]
I think I was able to set the path by doing, `LD_LIBRARY_PATH=/usr/local/lib/ ./PatcherGUI` to apply the patch.

However, I'm getting this on the debug log:

```
Executing external DecompressLZO program:
"/home/computer/PatcherGUI/binaries/DecompressLZO" "xcomgame.upk" "/home/computer/.local/share/Steam/steamapps/common/XCom-Enemy-Unknown/xcomgame/cookedpcconsole/xcomgame.upk"

DecompressLZO by wghost81 aka Wasteland Ghost
Usage: DecompressLZO [-h] [-i <str>] [-o <str>] <input file or pattern>
  -h, --help        	get usage help (this text)
  -i, --input=<str> 	set input dir
  -o, --output=<str>	set output dir
Unexpected parameter '/home/computer/.local/share/Steam/steamapps/common/XCom-Enemy-Unknown/xcomgame/cookedpcconsole/xcomgame.upk'

```

It looks like it's missing an option or I set it up wrong.

**Comment by wghost** [comment]
From the UPKUtils readme: The updated versions of the tools might not be working properly with PatcherGUI. Use the v7.3 sources released on Apr 10, 2015 for that purpose.

**Comment by chknatwork** [comment]
Awesome. Didn't really know what to expect when I read this so I figured it must be something I did wrong. It seems to work now. Thanks for making a great patcher!
